services:
  postgres:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app_internal

  backend:
    image: rust-app:latest
    container_name: rust-backend
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - postgres
    networks:
      - app_internal

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.nginx 
    container_name: frontend
    ports:
      - "${NGINX_PORT}:80"
    networks:
      - app_internal

networks:
  app_internal:
    driver: bridge 

volumes:
  postgres_data:
    driver: local
