FROM nginx:latest

# Install curl
RUN apt update && apt install -y curl && rm -rf /var/lib/apt/lists/*

# Copy configs and html if needed
COPY ./templates/index.html /usr/share/nginx/html/index.html
COPY ./templates/nginx.conf /etc/nginx/nginx.conf
